### ISSUE TITLE
リロードするとサインしてないですよ！と表示が出てしまう

### ISSUE THREAD

**Issue by Melonps** [Melonps/my_terminal#21]
![image](https://user-images.githubusercontent.com/95263124/189392379-e5f44506-323d-4a73-8321-13dc64cb471c.png)
参考画像

**Comment by yiRMT** [comment]
これ解決したはず: https://github.com/Melonps/my_terminal/commit/6c276bb03a52ebd1af018c3c95aa24cb9c963ef4

**Comment by Melonps** [comment]
閉じまつ
